dbdata:
  image: busybox:latest
  command: echo dbdata
  volumes:
    - /home/dimaip/docker/sfi.ru/lib/mysql:/var/lib/mysql

redis:
  image: redis

db:
  image: tutum/mariadb:latest
  ports:
    - 3306
  volumes_from:
    - dbdata
  environment:
    MARIADB_PASS: pass

webdata:
  image: busybox:latest
  command: echo webdata
  volumes:
    - /home/dimaip/docker/sfi.ru/data:/data

web:
  image: dimaip/neos:latest
  ports:
    - '8888:80'
  links:
    - db:db
    - redis
  volumes_from:
    - webdata
  environment:
    T3APP_NAME: 'sfi.ru'
    T3APP_BUILD_REPO_URL: 'https://github.com/sfi-ru/SfiDistr.git'
